version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin # change later and make it more secure
      RABBITMQ_DEFAULT_PASS: secret # change later and make it more secure
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs-server
    ports:
      - "2049:2049" # NFS
      - "111:111" # RPC portmapper
      - "20048:20048" # RPC mountd
    volumes:
      - nfs_storage:/nfs
    environment:
      - SHARED_DIRECTORY=/nfs
    privileged: true
    restart: unless-stopped
    command: >
      sh -c "
        echo 'Starting NFS server...' &&
        echo '/nfs *(rw,sync,no_subtree_check,no_root_squash)' > /etc/exports &&
        /usr/sbin/exportfs -arv &&
        /usr/sbin/rpcbind -w &&
        /usr/sbin/rpc.statd --no-notify --port 32765 --outgoing-port 32766 &&
        /usr/sbin/rpc.nfsd --debug 8 --no-udp --no-nfs-version 2 &&
        /usr/sbin/rpc.mountd --debug all --no-udp --no-nfs-version 2 --foreground
      "

  mcq-marking-system:
    build:
      context: ./mcq_marking
      dockerfile: Dockerfile
    volumes:
      - ./mcq_marking:/app
      - nfs_storage:/shared # Mount NFS storage
    depends_on:
      rabbitmq:
        condition: service_healthy
      nfs-server:
        condition: service_started
    environment:
      - RABBITMQ_URL=amqp://admin:secret@rabbitmq:5672 # change later and make it more secure
      - NFS_SHARED_PATH=/shared
    restart: unless-stopped
    privileged: true # Required for NFS mounting

volumes:
  rabbitmq-data:
  nfs_storage:
